### ISSUE TITLE
Discarded invalid value for parameter 'timestamp' 

### ISSUE THREAD

**Issue by phptek** [swilsonau/silverstripe-sentrylogger#1]
SilverStripe 3.4.1 + PHP 5.6 + Sentry 8.6.0

Whenever an exception is logged and reported within Sentry, viewing the error within Sentry itself, I see:

```
There was 1 error encountered while processing this event
    Discarded invalid value for parameter 'timestamp'
```

Wrapping a call to `strtotime()` around `$event['timestamp']` in `SentryLogger::_write()` makes this stop occurring.

**Comment by swilsonau** [comment]
Thanks for letting me know! If you wanted to submit a pull request, I'd happily accept it!
