### ISSUE TITLE
Upgrade to leatest PHP Raven SDK

### ISSUE THREAD

**Issue by phptek** [swilsonau/silverstripe-sentrylogger#5]
Sentry itself reports that I am using an "...old version of the PHP SDK"

**Comment by phptek** [comment]
I believe composer-updating to "sentry/sentry": "1.6.1" should sort this.

**Comment by swilsonau** [comment]
Thanks. I've updated this and released 1.1.0.

**Comment by phptek** [comment]
Cheers - do you have auto-updating enabled on Packagist? I don't see 1.1.0 on Packagist (https://packagist.org/packages/swilsonalfa/sentrylogger)
